# NOTE: This dockerfile relies on precompiled binaries already existing on the host at
# target/<docker-target>/externalip-manager.
# Example: target/linux/amd64/externalip-manager
FROM debian:bookworm-slim
ARG TARGETPLATFORM

COPY target/${TARGETPLATFORM}/externalip-manager /usr/local/bin/externalip-manager
RUN chmod +x /usr/local/bin/externalip-manager

# run unprivileged
USER 1001

CMD ["externalip-manager"]
