apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterexternalipsources.externalip.spacebird.dev
spec:
  group: externalip.spacebird.dev
  names:
    categories:
    - externalip-manager
    kind: ClusterExternalIPSource
    plural: clusterexternalipsources
    shortNames:
    - ceips
    singular: clusterexternalipsource
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Cluster-Wide source of external IP addresses for a given service
        properties:
          spec:
            properties:
              ipv4:
                description: Configure solvers for Ipv4 addresses
                nullable: true
                properties:
                  queryMode:
                    description: How the list of solvers should be queried. Can be "firstFound" (default) or "all". "firstFound" will query solvers until one succeeds and return only the addresses from this query. "all" will query all solvers and return all found addresses.
                    enum:
                    - firstFound
                    - all
                    nullable: true
                    type: string
                  solvers:
                    default: []
                    items:
                      oneOf:
                      - required:
                        - ipAPI
                      - required:
                        - dnsHostname
                      - required:
                        - loadBalancerIngress
                      properties:
                        dnsHostname:
                          description: Resolve a hostname through DNS and return the resulting A/AAAA records as IP addresses
                          properties:
                            host:
                              description: The host to resolve.
                              type: string
                          required:
                          - host
                          type: object
                        ipAPI:
                          description: Use a public "What-is-my-ip"-style service to deduce external IP addresses
                          properties:
                            provider:
                              description: The service to use for retrieving public IP information
                              enum:
                              - myIp
                              type: string
                          required:
                          - provider
                          type: object
                        loadBalancerIngress:
                          description: Use the ingress addresses assigned to the service in .status.loadBalancer.ingress as external IP addresses
                          type: object
                      type: object
                    type: array
                type: object
              ipv6:
                description: Configure solvers for Ipv6 addresses
                nullable: true
                properties:
                  queryMode:
                    description: How the list of solvers should be queried. Can be "firstFound" (default) or "all". "firstFound" will query solvers until one succeeds and return only the addresses from this query. "all" will query all solvers and return all found addresses.
                    enum:
                    - firstFound
                    - all
                    nullable: true
                    type: string
                  solvers:
                    default: []
                    items:
                      oneOf:
                      - required:
                        - ipAPI
                      - required:
                        - dnsHostname
                      - required:
                        - loadBalancerIngress
                      properties:
                        dnsHostname:
                          description: Resolve a hostname through DNS and return the resulting A/AAAA records as IP addresses
                          properties:
                            host:
                              description: The host to resolve.
                              type: string
                          required:
                          - host
                          type: object
                        ipAPI:
                          description: Use a public "What-is-my-ip"-style service to deduce external IP addresses
                          properties:
                            provider:
                              description: The service to use for retrieving public IP information
                              enum:
                              - myIp
                              type: string
                          required:
                          - provider
                          type: object
                        loadBalancerIngress:
                          description: Use the ingress addresses assigned to the service in .status.loadBalancer.ingress as external IP addresses
                          type: object
                      type: object
                    type: array
                type: object
            type: object
        required:
        - spec
        title: ClusterExternalIPSource
        type: object
    served: true
    storage: true
    subresources: {}
